### ISSUE TITLE
Homepage redesign

### ISSUE THREAD

**Issue by kcarcia** [isenseDev/rSENSE#1465]
"Everything about the homepage doesn't tell you what iSENSE does." - @jdalphon 

"Both the mobile and desktop homepages are useless" - @NatTuck

**Comment by kcarcia** [comment]
Update: Homepage has been code reviewed. We are waiting on images to move forward. @fgmart any updates with the images for the homepage?

**Comment by bdonald25** [comment]
Testers: Test the homepage and make sure it looks good on all screen sizes.

**Comment by asalani93** [comment]
PASSED testing on Chrome 45.0.2454.101 (linux).
suggestion: 2 boxes per row for featured and curated projects on small screen size, or 6 items total
also, but the app buttons on the same row, and add some space between them

**Comment by pat-son** [comment]
PASSED testing on Chrome 46.0.2490.80 (Mac OSX 10.10.5).
Looks good. Maybe add a paragraph somewhere explaining what iSENSE is?

**Comment by tylerpuleo** [comment]
PASSED That's fine

**Comment by JasonD94** [comment]
PASSED testing on Chrome 46.0.2490.80 (linux).
Looks pretty good. The images stretch a lot in between small / medium sizing though. I would also agree that medium size should be 2 rows instead of 3, looks weird with only 4 featured projects / curated projects. 6 featured projects could also work, since 3 by 2 would look pretty good in the medium size.
