### ISSUE TITLE
Enhance axis labeling/mouseover tooltips for histogram

### ISSUE THREAD

**Issue by ivanrudnicki** [isenseDev/rSENSE#1470]
Users would have an easier time understanding histograms, I believe, if the x axis labeling were clearer or the tooltips more detailed. As it is now, depending on the bin size, all or just a handful of the bars in a histogram have labels on the x axis. Even for a bar with a label, the user has to mentally calculate the lower and upper values represented in the stack: lower value =  label - (bin size/2) and upper value = label + (bin size/2). This is kind of hard. I expect that enhancing the high charts axis labels might be difficult, but could the tooltips provide more detail on the range of values represented in each stack?

**Comment by pat-son** [comment]
We will either make the x-axis ticks positioned more appropriately or add a new label on the tooltip. Definitely gonna do this soon.

**Comment by VictoriaAlbanese** [comment]
Would something like this work?

Fieldname: ...
Group ID: ...
Bin #: ...
Bin Range: (lower bound) - (upper bound)
Data Points in Bin:

I think adding a range option would solve your problem, and that rephrasing "# occurances" to "data points in bin" might be a bit more descriptive to younger audiences who aren't familiar with histograms in the first place.  

Also, currently the last field in the tooltip looks like this: 
(group id): 1
which doesn't seem to make much sense.  It might make more sense to include it on the tool tip as I did above, instead of saying (I presume) that this represents 1 data point taken from whatever group.

**Comment by doug-salvati** [comment]
In the process of working on #2555, I was annoyed by this too began reworking the format like this.  I'm redoing the tooltips to show "Data Points in Bin" when there are multiple data points consolidated into a block, and shows the actual value if there is only one data point in the bin.

I would like to add the range feature you implemented.  We should combine our code for the design to close this, and I'll PR the logic behind #2555 later on down the road...

![imageedit_2_4405756149](https://cloud.githubusercontent.com/assets/17438678/22299457/24085926-e2f2-11e6-8b45-aad823c36611.jpg)

**Comment by doug-salvati** [comment]
Testers: make sure range is correct in the tooltip, and that count per bin displays as well (only happens if the bin is big enough)

**Comment by pat-son** [comment]
PASSED testing on Chrome 54.0.2840.100 (linux).

**Comment by VictoriaAlbanese** [comment]
PASSED testing on Chrome 54.0.2840.71 (linux).
Works perfectly

**Comment by doug-salvati** [comment]
PASSED testing on Safari 10.0.3 (mac).
