### ISSUE TITLE
Regression curves don't take into account log-y-axis mode

### ISSUE THREAD

**Issue by fgmart** [isenseDev/rSENSE#1624]
E.g., try looking at http://isenseproject.org/visualizations/317

Turn off the girl data

check "Logarithmic Y axis".  interesting, the graph now forms a straight line :)

Now try a best fit with line.... whoops.

**Comment by JKinsman** [comment]
After investigating the issue today, It turns out that regression lines on visualizations with a logarithmic y-axis are being drawn correctly.  This is working as intended.  I had a conversation about this with @fgmart today, and he requested the regression controls be enabled on a visualization with a logarithmic y-axis.
