### ISSUE TITLE
Deleting users doesn't

### ISSUE THREAD

**Issue by asalani93** [isenseDev/rSENSE#1773]
**General description:**
Deleting a user doesn't really do as advertised.  It removes projects and saved vises as it should, but:
* you can still sign in using the garbage email address it changes your user to
* you can change your email to something else to effectively become undeleted
* you don't even need to know your deleted email to do the above if you're already signed in
* you can make projects and saved vises after you've been deleted
* you can make a saved vis for a project that has already been deleted

**live/dev/localhost:** live/dev
**iSENSE Version:** 5.6
**Logged in (Y or N):** Y and N
**Admin (Y or N):** Kind of?

**OS:** all
**Browser/Version:** all

**Steps to Reproduce:**
1. log in with a user
2. have someone delete said user while still logged in
3. go into your account settings and change your email to what it was
4. create some projects or whatever
5. things still work

-alternatively-
1. delete a user you've created
2. log out and log in to the deleted user, using the weird garbled stuff you get when you delete a user as the email
3. do things as stated above

**Associated Image(s):** N/A

**Comment by kcarcia** [comment]
TESTERS: Verify you can no longer do the following:

- you can still sign in using the garbage email address it changes your user to
- you can change your email to something else to effectively become undeleted
- you don't even need to know your deleted email to do the above if you're already signed in
- you can make projects and saved vises after you've been deleted
- you can make a saved vis for a project that has already been deleted
(taken from above, written by anthony)

As a reminder, here's how this works:
"You still can't delete a project with data sets by default. If you delete a user, all of his/her data sets are deleted first. If it is found that now his/her project can be deleted (i.e. only that user contributed to it), it gets deleted. Otherwise, since that project has contributions from other users, ownership switches to admin. Then the user gets deleted. We should note only admins can delete users though."

**Comment by stowellm** [comment]
PASSED testing on Chrome 42.0.2311.135 (linux).
DISREGARD THIS IS JUST A TEST

**Comment by JKinsman** [comment]
PASSED testing on Chrome 42.0.2311.135 (Mac OSX 10.10.2).

**Comment by jdaigneau** [comment]
PASSED testing on Chrome 42.0.2311.90 (mac).
