### ISSUE TITLE
Deleting a user doesn't delete projects or saved vises

### ISSUE THREAD

**Issue by asalani93** [isenseDev/rSENSE#1794]
**General description:** Deleting a user doesn't delete projects or saved vises.  You can't see the projects or vises from the index pages, but the URL still works and they're still in the user's page because #1773.  Also, it seems as if media objects are *sometimes* deleted.  For example, this project:
http://rsense-dev.cs.uml.edu/projects/838
had it's media object deleted, but there was another one that still has it's media object.

**live/dev/localhost:** dev
**iSENSE Version:** 5.7.74
**Logged in (Y or N):** Y/N
**Admin (Y or N):** Y/N

**OS:** Ubuntu 14.04.1 x64
**Browser/Version:** Chrome 36

**Steps to Reproduce:**
1. Create a user.
2. Create a project
3. Give that project a dataset or two.
3. Create a saved vis from that project.
4. Give each a media object.
5. Delete the user.
6. Observe as the projects and vises are still there, and the media objects may or may not still be there.

**Associated Image(s):**
nah

**Comment by stowellm** [comment]
Kind of goes with #1773

**Comment by kcarcia** [comment]
TESTERS: 
If you delete a user, please verify
(1) their empty projects should just be deleted
(2) their projects with data sets only contributed by him/her should be deleted
(3) their projects with data sets contributed by other users will not be deleted; the owner will be admin

This is how this works:
"You still can't delete a project with data sets by default. If you delete a user, all of his/her data sets are deleted first. If it is found that now his/her project can be deleted (i.e. only that user contributed to it), it gets deleted. Otherwise, since that project has contributions from other users, ownership switches to admin. Then the user gets deleted. We should note only admins can delete users though."

**Comment by stowellm** [comment]
PASSED testing on Chrome 42.0.2311.135 (linux).
DISREGARD THIS IS JUST A TEST

**Comment by JKinsman** [comment]
PASSED testing on Chrome 42.0.2311.135 (Mac OSX 10.10.2).

**Comment by jdaigneau** [comment]
PASSED testing on Chrome 42.0.2311.90 (mac).
