### ISSUE TITLE
Forumulaic fields

### ISSUE THREAD

**Issue by jaypoulz** [isenseDev/rSENSE#1848]
**General description:**
One of the teachers at the workshop brought this up (again). I figured it deserved an issue. Essentially, teachers want ability to define a field/column as a formula (maybe using spreadsheet syntax).

**live/dev/localhost:** N/a
**iSENSE Version:** N/a
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** N/a
**Browser/Version:** N/a

**Steps to Reproduce:**
1. Hitting edit fields should bring up an option for this.

**Associated Image(s):** None

**Comment by pat-son** [comment]
I tried a test with conditionals (in the project "Winter Weather Data"), and nothing is being output. Either I wrote the formula wrong, or the data is not being calculated in the backend. Also, I feel like the Formula reference is written kind of weird. I get that you wrote "`(+)(l: number, r: number) -> number`" because the plus is a function or something, but could you at least also specify that you can write it in the normal, human way too (lvalue + rvalue -> number)?"

**Comment by pat-son** [comment]
Also, I think that users should be able to see what the formulas are on someone else's project.

**Comment by tylerpuleo** [comment]
Formula field names get auto generated to the same names as regular fields. For example the first regular number field is Number_1 and the first formula field is Number_1 so you get an error that two fields have the same name.

**Comment by tylerpuleo** [comment]
After I create a formula and save it I would like to see it instead of just the edit icon.

**Comment by tylerpuleo** [comment]
![image](https://cloud.githubusercontent.com/assets/7584536/14321554/b1ac68f0-fbe7-11e5-87a6-0cfeb43202c9.png)

I can drag these fields around. I don't think this was desired

**Comment by bdonald25** [comment]
I found the same things Tyler already pointed out. I think the default naming for formula fields should be something like Formulaic_Number_1 and Formulaic_Text_1 so they do not conflict if you don't rename your regular fields.

Also if you have Number_1 - Number_2 as a formula and a particular value of 1 is empty and the corresponding number2 = 6 then the result is -6. It should be nothing because one of the values was nothing and you did not supply the formula with a default value for Number_1 in the formula. 

It is also not clear how to give a field a default value in the formula.  

The formula page should have a link to the docs.

**Comment by bdonald25** [comment]
![2016-04-06](https://cloud.githubusercontent.com/assets/4121924/14322120/baf3ca46-fbe9-11e5-893c-8df6ffbc69ef.jpg)
I am not sure how the reference naming is done

**Comment by doug-salvati** [comment]
Concatenating an int such as 1 to a string makes it display as 1.0 in the concatenated string.  This might not be what the user wants.

“Infinity" results (such as divide by zero) are blank in the table visualization.  It might be better to give the user a warning or some indication of why the field is blank.

Your approximation for storing the value of pi leads to results the user may not expect, for instance sin(pi) returns 1.22344…e-16 rather than 0.  I think it's worth making these types of expressions evaluate to 0 / display as zero.

**Comment by asalani93** [comment]
I agree on the first and third issues.  I've been debating on whether or not to override how ruby formats floats as strings for whole numbers, and that's very easy tbh.  For the third one, I'll use the project's precision settings to round off numbers when displayed to the user.

However, the second will probably stay as is. FF is designed to handle cases of incomplete or missing data without the user being given an error message.  For sufficiently large data sets, that many errors could be overwhelming. A consequence of this is that I can't really do much in the case of dividing by zero.

Thank you all for testing, by the way!

**Comment by VictoriaAlbanese** [comment]
I am going through the reference page to look for issues.

When trying to do the (l: timestamp) + (r: number) -> timestamp an error occured: With formula field cat_timestamp: returned type timestamp, expected type [:number].  It seems like the timestamp formula field hasn't been implemented yet, so I would add a note in the docs indicating this (and anything else of a similar nature that returns a non number or text field)

In addition, there is a timestamp - timestamp option.  Since the user isn't allowed to have more than one timestamp per project, isn't this a bit moot?  I think that part in the docs should be taken out.

**Comment by asalani93** [comment]
For the first one, there can only be one timestamp field per project, so there won't ever be a formulaic timestamp.  However you can do stuff like `day(Timestamp + 500)` to get the day of the given timestamp plus some seconds. For the second one, you can do something like `Timestamp - prev(Timestamp)` to get the number of seconds between two data points. The first one is included for completeness, but the second I think could be useful.

This stuff will definitely be thrown in the docs though! Thanks for pointing them out.

**Comment by bdonald25** [comment]
Testers: Try to break formula fields.

**Comment by doug-salvati** [comment]
PASSED on Chrome Mac OSX

**Comment by pat-son** [comment]
PASSED testing on Chrome 50.0.2661.86 (OSX 10.11.3).
Works pretty good.
