### ISSUE TITLE
Project with no title cannot be deleted

### ISSUE THREAD

**Issue by jaypoulz** [isenseDev/rSENSE#1890]
**General description:** Projects with no title cannot be deleted.

**live/dev/localhost:** live
**iSENSE Version:** v5.12
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** X11
**Browser/Version:** Firefox 34.0

**Steps to Reproduce:** 
1. Create a project titled `<script>alert(1);</script>`
2. Be amazed as the project is created, but your title is left blank.
3. Try to delete the project.
4. Weep as it doesn't delete because it has no name.

**Comment by kcarcia** [comment]
TESTERS: Follow those exact steps listed above to test.

**Comment by asalani93** [comment]
PASSED testing on Chrome 39.0.2171.71 (Ubuntu 14.04.1).

**Comment by asalani93** [comment]
projects still aren't deleted

**Comment by kcarcia** [comment]
PASSED testing on Chrome 29.0.1547.57 (mac).

**Comment by kcarcia** [comment]
@asalani93 what do you mean by "projects still aren't deleted"? Did you mean to check FAILED on this one?

**Comment by asalani93** [comment]
Sorry, didn't word that right.  Projects with no title are deleted.

You can still access a project by its ID - none of the projects seem to
actually be deleted, just hidden.  I'm not sure if that's in the scope of
Mike's PR or not.

**Comment by kcarcia** [comment]
@asalani93 Will look into this. Nice catch!

**Comment by stowellm** [comment]
What should be patched is that deleting a project from the project edit or user page should actually remove the project.  What is *not* addressed by the patch is deleting a user also deleting his or her respective projects.  That latter should be addressed in the much-talked-about-but-not-happening-yet patch where we actually delete everything on iSENSE when users choose to delete stuff (i.e. projects, data sets, media, the users themselves, etc.).

@asalani93 - when I delete a project as I'm mentioned in the former piece of the above comment, I cannot reference them again by ID (I just get an exploding beaker guy - which is good, because nothing should live at that URL anymore).  Even when I try accessing the just-deleted project via a `Project.find(#ID_OF_DELETED_PROJ#)` in a `rails c` REPL, I get an `ActiveRecord::RecordNotFound` (which is again, appropriate).  If you deleted a project through the edit or user's project page, how were you able to reference it again?

**Comment by stowellm** [comment]
PASSED testing on Chrome 40.0.2214.93 (OSX Yosemite 10.10.1).

**Comment by kcarcia** [comment]
@stowellm Thank you for that thorough explanation, Mike. @asalani93 can you provide us an example of how you can still access a project by its ID please?

**Comment by asalani93** [comment]
PASSED testing on Chrome 39.0.2171.71 (UUBBUUNNTTUU 1144..0044).

**Comment by stowellm** [comment]
PASSED testing on Chrome 40.0.2214.93 (OSX).

**Comment by JKinsman** [comment]
PASSED testing on Safari 8.0.3 (Mac OSX 10.10.2).
