### ISSUE TITLE
"Select All" is broken on tables

### ISSUE THREAD

**Issue by bdonald25** [isenseDev/rSENSE#1980]
**General description:** "Select all" is broken on tables.

**live/dev/localhost:** live
**iSENSE Version:** v6.0
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Macintosh
**Browser/Version:** Chrome 41.0.2272.35

**Steps to Reproduce:** If you click a dataset to disable it and then re-enable the same dataset, the select all button will not re-enable but will act like it is enabled. (ie, when you select it, all the datasets become deselected and vice versa)

393

**Comment by stowellm** [comment]
Steps to Reproduce (modified since it took me a while to understand Bobby's instructions):
1. Visualize a group of data sets with some data and multiple fields
2. Go to table
3. Make sure #Check All is selected along with the other fields
4. Deselect one field. Note #Check All is also deselected
5. Reselect that field.  Note #Check All is still deselected
6. Check off #Check All. Note the bug: all the other fields are now *deselected* and this checkbox's functionality has reversed

**Comment by kcarcia** [comment]
TESTERS: Please follow the beautiful steps to reproduce @stowellm posted above.

**Comment by stowellm** [comment]
PASSED testing on Internet Explorer 11.0 (windows 7).

**Comment by asalani93** [comment]
PASSED testing on Chrome 39.0.2171.71 (Ubuntu 14.04.1 x64).

**Comment by tylerpuleo** [comment]
PASSED testing on Chrome 38.0.2125.111 (linux).

**Comment by JKinsman** [comment]
PASSED testing on Safari 8.0.3 (Mac OSX 10.10.2).

**Comment by jdaigneau** [comment]
PASSED testing on Chrome 40.0.2214.94 (Max OSX 10.9.4).
