### ISSUE TITLE
API Contrib Key Takes Project ID in url and as a param

### ISSUE THREAD

**Issue by tylerpuleo** [isenseDev/rSENSE#1989]
General description: Project ID listed twice in Contrib key api call "/api/v1/projects/XX/add_key"

live/dev/localhost: live
iSENSE Version: v6.0
Logged in (Y or N): Y
Admin (Y or N): N

OS: Ubuntu 14.04 (Jacascript)
Browser/Version: Chrome 41.0.2272.43

Steps to Reproduce: Look at docs. Need to pass ID twice.

**Comment by jdalphon** [comment]
@bdonald25 I will consider your pull if you can answer this question. Could this, at all, cause a current working consumer of the API to now fail? Basically you have to prove that the call
`isenseproject.org/api/v1/projects/3/add_key?...  contrib_key: { project_id: something other than 3, ...} `
failed previously (error case, not just do the wrong thing)
I know this is dumb but if someone literally typed `isenseproject.org/api/v1/projects/3(or XX)/add_key...some other number` what would happen. 

Looking at the code I know the answer, but this is a good test to make sure we are not breaking things for users. Please post the output from tests. 

Extra credit (ill buy you a coffee) what happens if you make the call owning the two different projects. i.e.  `/api/v1/projects/2/add_key project_id: 3` where you own 2 and 3.

**Comment by bdonald25** [comment]
@jdalphon 

Before it was using the param "project_id" not the "id" param in the url. 
/api/v1/projects/2/add_key project_id: 3  -> will currently create a key for project 3
Now it uses the project id from the url, so now it will create the key for project 2. 

The proper way I should have done it if I was worried about compatibility would be to change the url parameter to "project_id". However, I went with "id" because that is what all of the other api calls use as a parameter and this api call has only existed for 10 days so I am not worried about it breaking anything.

**Comment by jaypoulz** [comment]
@bdonald25 That's fine, but let's be more mindful about this in the future. You're right that it is unlikely that anyone depends on this, but as a general rule of thumb, anything we release out live should be considered supported. Is the update for add key already live?

**Comment by bdonald25** [comment]
@jaypoulz No this update is currently pending as a pull request. Keep in mind it would only have unintended consequences if someone had a different id for both project parameters. If they had previously used the same project id in the url as the one they passed as a parameter it will still work.

**Comment by jaypoulz** [comment]
I left a comment in the pull request as to how to fix this without 'breaking' anything. You're are right that having both params be different is a problem, but for that we just set a default.

**Comment by jdaigneau** [comment]
PASSED testing on Chrome 40.0.2214.115 (mac).
