### ISSUE TITLE
API Typo in /api/v1/projects/XX/jsonDataUpload

### ISSUE THREAD

**Issue by tylerpuleo** [isenseDev/rSENSE#1990]
General description: API typo "Data is a hash of field_id -> data array pairs. FIELD_ID and FIELD_ID_2 would be replaced with ids for their respective filds." filds instead of fields.

live/dev/localhost: live
iSENSE Version: v6.0
Logged in (Y or N): Y
Admin (Y or N): N

OS: Ubuntu 14.04
Browser/Version: Chrome 41.0.2272.43

Steps to Reproduce: Type

**Comment by kcarcia** [comment]
TESTERS: Go to http://rsense-dev.cs.uml.edu/api/v1/docs and proof the two POST Data Sets	/api/v1/projects/XX/jsonDataUpload sections. If you're feeling ambitious, feel free to proof all the documentation.

**Comment by stowellm** [comment]
PASSED testing on Internet Explorer 11.0 (windows 7).
But some comments:
- /api/v1/projects/XX --- "•XX should be replaced with the ID for the project. Or set id as a GET variable" --- incoherent
- /api/v1/fields/XX --- same as above
- /api/v1/projects --- "Response:  Projects (array)" --- JSON format this please
- /api/v1/fields --- "•restrictions - Currently text fields only. Defines accepted values "blue,green,red" will force the project to accept only those values" --- incoherent
- /api/v1/data_sets/append --- put "none" or "n/a" or something instead of blank space under "Notes"
- /api/v1/users/myInfo --- same as above
- /api/v1/media_objects --- "•type - either "project", or "data_sets" --- cringe-worthy grammar

**Comment by asalani93** [comment]
PASSED testing on Chrome 39.0.2171.71 (Ubuntu 14.04.1 x64).

**Comment by tylerpuleo** [comment]
PASSED testing on Chrome 38.0.2125.111 (linux).

**Comment by JKinsman** [comment]
PASSED testing on Safari 8.0.3 (Mac OSX 10.10.2).

**Comment by kcarcia** [comment]
@bdonald25 @stowellm Will open a new bug with these changes.

**Comment by jdaigneau** [comment]
PASSED testing on Chrome 40.0.2214.94 (Max OSX 10.9.4).
