### ISSUE TITLE
Should Extend File Type Regex to Match Different Casing

### ISSUE THREAD

**Issue by kcarcia** [isenseDev/rSENSE#2061]
**General description:** jpgs are supported but not JPGs. Regexes should be modified to accept different casing.

**live/dev/localhost:** live
**iSENSE Version:** v6.3
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** Macintosh
**Browser/Version:** Chrome 41.0.2272.89

**Steps to Reproduce:**
1. Go to a project.
2. Click Add File under media.
3. Select a file with a .JPG extension.

**Comment by stowellm** [comment]
In addition to this: when checking whitelisted file types, be sure to check the *last* part of the extension as opposed to whatever is after the first dot.

e.g. Right now `thisIsNotA.gif.doc` could be a valid document but since it find `.gif`, it is not accepted.
Same goes the other way: `thisIsNotA.doc.gif` is accepted despite being a gif.

**Comment by kcarcia** [comment]
TESTERS: A few things to test here:
(1) The file types we support should be accepted regardless of casing. For example, a .jpg or .JPG are valid file types. Verify this is working.
(2) The last part of the extension should be checked. As Mike described above, thisIsNotA.gif.doc could be a valid document but since it finds .gif, it is not accepted.
Same goes the other way: thisIsNotA.doc.gif is accepted despite being a gif. Please verify the last part of file extension is checked by using Mike's example as a guide.

**Comment by stowellm** [comment]
PASSED testing on Chrome 41.0.2272.101 (Ubuntu 14.04 LTS).

**Comment by JKinsman** [comment]
PASSED testing on Safari 8.0.3 (Mac OSX 10.10.2).
