### ISSUE TITLE
Group by contributors in vis

### ISSUE THREAD

**Issue by stowellm** [isenseDev/rSENSE#2088]
**General description:** There should be an option to group by contributors in a vis.  For example, if 5 users under contributor key "A", 7 users under contributor key "B", user "Little Timmy," and user "Little Billy" contribute data sets, the vis should have a group-by option for contributors that would list "Key: A, Key: B, User: Little Timmy, User: Little Billy."

**live/dev/localhost:** dev
**iSENSE Version:** v6.5
**Logged in (Y or N):** N
**Admin (Y or N):** N

**OS:** Ubuntu 14.04 LTS
**Browser/Version:** Chrome 41

**Steps to Reproduce:**
1. Make a project with some number fields.  Add location for pizzazz.
2. Add two contributor keys.
3. Contribute multiple data sets with the two keys and two additional users.
4. Visualize the data.  Start on Scatter, but it should work for all other relevant vises.
5. Note there should be a "Contributors" group-by option once this feature is complete.

**Associated Image(s):**
Once implemented, should look like this:
![lolthing](https://cloud.githubusercontent.com/assets/1039162/6941530/b72a9454-d84e-11e4-89de-a477a593cffa.png)

**Comment by bdonald25** [comment]
Testers: Change the group by option to group by contributor. Make sure it works for new and old vises, new and old default vises, and new and old saved vises.

Also make sure that all the old saved vises and default vises are the same on live and dev. They should have all the same options for all their tools other than the option to group by contributor. If different things are checked off for a saved vis on live and dev then that is a bug.

**Comment by jaypoulz** [comment]
@bdonald25 was this patch based on Mike's previous attempt? Because this is awesome! :+1: I took a quick look at the migration - gawd that is a monster. Sorry about that. I meant to fix this with 2.0, but our history of quick and dirty vis configurations made this quite a beast to tackle. Nice work!

**Comment by bdonald25** [comment]
@jaypoulz It was loosely based on Mikes. I redid it from scratch without looking at his because Mike wasn't sure where the problem was but I noticed as I was almost done that mine was very similar to his, so I used his as reference to finish it off. His attempt was 90% of the way there, he had just skipped over some things that needed to be migrated.

**Comment by jaypoulz** [comment]
I cannot :+1: this enough! :smile_cat:

**Comment by pat-son** [comment]
PASSED testing on Firefox 44.0.2 (Mac OSX Yosemite 10.10.5).

**Comment by bdonald25** [comment]
PASSED testing on Chrome 48.0.2564.109 (linux).

**Comment by bdonald25** [comment]
PASSED testing on Chrome 48.0.2564.109 (linux).

**Comment by JasonD94** [comment]
PASSED testing on Chrome 48.0.2564.97 (Linux Ubuntu 14.04 LTS).

**Comment by bdonald25** [comment]
This pull request needs to be looked at a little more so I am going to hold off until next release.

**Comment by JasonD94** [comment]
PASSED testing on Chrome 48.0.2564.109 (linux).
