### ISSUE TITLE
Contributor key error messages need UI TLC

### ISSUE THREAD

**Issue by isenseanon** [isenseDev/rSENSE#2100]
**General description:** I made a contributor key, but it does not work. Students can not submit data using this key. When I try to edit the key I get 2 error messages that say the key is too short (minimum one character necessary)...the key I made is 2015 (so its long enough) but does not work. How can I edit the key?

**live/dev/localhost:** live
**iSENSE Version:** v6.6
**Logged in (Y or N):** Y
**Admin (Y or N):** Y

**OS:** Windows
**Browser/Version:** Internet Explorer 11.0

**Steps to Reproduce:** edit project page

2464

**Comment by jdalphon** [comment]
Just got off the phone with @jaypoulz. 

I just tested on IE11 on windows and everything appears to be working. I am thinking that there was a special character of some sort that may have gotten sanitized. We need more information if possible to solve this bug.

**Comment by jaypoulz** [comment]
We believe this to be caused by an empty 'label' field, and should update the error message appropriately.

**Comment by kcarcia** [comment]
@jaypoulz @jdalphon Did you contact this person to get more information/to let them know we're working on it?

**Comment by jaypoulz** [comment]
@kcarcia yep, I'll forward you the convo

**Comment by jaypoulz** [comment]
The source of this issue is that creating contributor keys is confusing for users on older versions of IE. As you can see below, the hint text just looks like regular text to users. The other issue is that the error messages aren't localized to the create key area. It would probably be other adding some js to call 'errorFlash' on the text boxes if they are empty. Maybe we pop up some errors in red text just below the boxes, it's probably disorienting for users to be pulled back to the top of the page. Also, the error messages aren't particularly helpful. :smile: 
![badui](https://cloud.githubusercontent.com/assets/1039164/7099078/693e15dc-dfb9-11e4-91c6-9a5576245b1d.png)

**Comment by bdonald25** [comment]
Testers: Try creating a key and leave either the label and/or the key blank. Make sure that the error message is clear and helpful.

**Comment by KatherineBrunelle** [comment]
PASSED testing on Safari 8.0 (mac).

**Comment by asalani93** [comment]
PASSED testing on Chrome 42.0.2311.90 (linux).

**Comment by jaypoulz** [comment]
PASSED testing on Firefox 40.0 (linux).
