### ISSUE TITLE
Group selection results in an incongruency with group colors

### ISSUE THREAD

**Issue by asalani93** [isenseDev/rSENSE#2220]
**General description:** Changing the selected groups on pie chart randomizes the colors of the slices of the pie

**live/dev/localhost:** live
**iSENSE Version:** 7.1
**Logged in (Y or N):** N
**Admin (Y or N):** N

**OS:** Ubuntu 14.04.1 x64
**Browser/Version:** Chrome 43 x64

**Steps to Reproduce:**
* go to pie chart w/ more than one group
* unselect and reselect a group
* observe as the colors no longer match what they should be

**Associated Image(s):**

**Comment by JasonD94** [comment]
It looks like this isn't random. It has to do with an array that holds the order of the groups / colors (data.groupSelection). If you have 3 groups at first, the array looks like [0, 1, 2]. If you then remove the middle item, the array becomes [0, 2]. If you then add the middle item back, it pushes it to the back of the array and the array ends up as [0, 2, 1] instead of the original [0, 1, 2].

**Comment by bdonald25** [comment]
Testers: Go to a pie chart vis. Un-check fields and recheck them. Make sure the colors of all the slices did not change.

**Comment by asalani93** [comment]
PASSED testing on Chrome 45.0.2454.101 (linux).

**Comment by pat-son** [comment]
PASSED testing on Chrome 46.0.2490.80 (Mac OSX 10.10.5).

**Comment by JasonD94** [comment]
PASSED testing on Chrome 46.0.2490.80 (linux).
