### ISSUE TITLE
Infamous "Contribution Key Bug"

### ISSUE THREAD

**Issue by isenseanon** [isenseDev/rSENSE#2298]
**General description:** The program won't let me put in any data set names. It says it must be unique to the project, but even made up names won't work

**live/dev/localhost:** live
**iSENSE Version:** v7.4.1
**Logged in (Y or N):** Y
**Admin (Y or N):** N

**OS:** X11
**Browser/Version:** Chrome 45.0.2454.98

**Steps to Reproduce:** entering data

498

**Comment by jdalphon** [comment]
So what is actually going on here has nothing to do with the contribution keys. It has just manifested itself when we have rooms full of users that are entering data using a contribution key. 

The problem is actually with field restrictions either on the tables JS or when the data makes it to the server. I will determine this in a bit. 

Steps to reproduce:
1)Create a project with a text field and restrictions. 
2)Log in or use contribution key
3)Use the manual entry option to contribute data. 
4)Click on the text field dropdown in any row of the text field's column then click away. 
5)Type a name and submit the form. 

You will get the error. And its not the error that is reported, so theres that.

**Comment by fgmart** [comment]
Here's more from Jim in a chat with me:


yup...so the problem manifests when you have a text field with restrictions
if you are doing manual entry and you click any text field with restrictions without actually making a selection it breaks. So say i click out of a dropdown by selecting another cell. Unless i delete that row or go back and make a selection, it will break

**Comment by bdonald25** [comment]
The drop down was adding a null value to the data which was breaking something after the data was validated to be ok and before it was uploaded. We were assuming that if it passed validation but failed to upload then it must have been because of a duplicate title. 

I fixed the problem by replacing any null values with empty strings as it parsed the data from the grid.

**Comment by fgmart** [comment]
excellent!

**Comment by asalani93** [comment]
PASSED testing on Chrome 45.0.2454.101 (Ubuntu 15.04).
