### ISSUE TITLE
HTML project title of window should follow case of project name

### ISSUE THREAD

**Issue by fgmart** [isenseDev/rSENSE#2301]
Looks like the code that pulls the project name and makes it be the title of the web window is playing with the case.

E.g. my project is titled "MA PARCC 2015" but it shows up at "Ma parcc 2015" in browser window.

The case should not be changed.

![screenshot 2015-11-11 at 6 27 52 pm](https://cloud.githubusercontent.com/assets/1038856/11106194/3d0859b8-88a2-11e5-99ac-c83b507319ed.png)

**Comment by pat-son** [comment]
The issue was in [app/helpers/application_helper](https://github.com/isenseDev/rSENSE/blob/952cd48f0323ecf9c3a4d5dd1acffea0a39af12c/app/helpers/application_helper.rb#L131). Every project title has having "capitalize" called on it, which changes the first character to uppercase and the rest to lowercase.

I fixed it by just removing the call to capitalize.

**Comment by asalani93** [comment]
PASSED testing on Chrome 45.0.2454.101 (Ubuntu 15.04).
Should be the same for visualizations
