### ISSUE TITLE
when using group-by, x axis of bar chart should display grouping name

### ISSUE THREAD

**Issue by fgmart** [isenseDev/rSENSE#2328]
Check out the vis below (also at http://isenseproject.org/visualizations/1094).

This is showing a group-by of category "4b. efficient lighting".

there are three possible answers, and the total num of people in each option is summed up and displayed.

So far, so good.

But the x-axis key says "1. How many people in your home". As does the Y-axis.

This *should* be displayed for the Y-axis, because that's the analysis method (the sum of this field).

But it should not be on the x-axis too. Instead, the grouping category should be displayed.

![group-by](https://cloud.githubusercontent.com/assets/1038856/11980618/257771ba-a96a-11e5-84cc-445832b4f638.png)

**Comment by bdonald25** [comment]
The reason it says it on the x-axis is because you can view multiple things on the y-axis at the same time. I agree it is confusing when you are only looking at one thing. 

See the image below. There is no data for semester, but you can see where the bars would be. 

![screenshot from 2015-12-23 11-55-50](https://cloud.githubusercontent.com/assets/4121924/11980927/67ab3a9c-a96c-11e5-9e24-811d2c21711d.png)

**Comment by bdonald25** [comment]
Testers: If you go to a bar chart and only select one field. It should not show the field name on the x-axis like in the image above.

**Comment by bdonald25** [comment]
Testers: If you go to a bar chart and only select one field. It should not show the field name on the x-axis like in the image above.

**Comment by pat-son** [comment]
PASSED testing on Firefox 44.0.2 (Mac OSX Yosemite 10.10.5).

**Comment by bdonald25** [comment]
PASSED testing on Chrome 48.0.2564.109 (linux).

**Comment by bdonald25** [comment]
PASSED testing on Chrome 48.0.2564.109 (linux).

**Comment by JasonD94** [comment]
PASSED testing on Chrome 48.0.2564.97 (Linux Ubuntu 14.04 LTS).
