### ISSUE TITLE
New User System (Devise)

### ISSUE THREAD

**Issue by bdonald25** [isenseDev/rSENSE#2370]
**General description:** New User System (Devise)

**live/dev/localhost:** live
**iSENSE Version:** 7.7.2
**Logged in (Y or N):** N/A
**Admin (Y or N):** N/A

**OS:** X11
**Browser/Version:** Chrome 49.0.2623.87

**Steps to Reproduce:** 

393

**Comment by bdonald25** [comment]
Testers: Make sure that signing in with Google works and everything to do with a user is the same as before. (signing in, logging out, ect.)

**Comment by VictoriaAlbanese** [comment]
Logging in normally works
Forgetting your password fails after you input your email address, sending me to this page:
![forgot_password](https://cloud.githubusercontent.com/assets/12720180/14918990/9e49bc4e-0df4-11e6-832d-fee68bde9d78.png)
Signing in with google doesn't work, giving me this message: "Could not authenticate you from GoogleOauth2 because "Invalid credentials"."
-DOES NOT PASS

**Comment by VictoriaAlbanese** [comment]
FAILED testing on Chrome 48.0.2564.116 (linux).
Logging in/out normally works
Registering works

Forgetting your password does not work; it fails after you give the site your email.
Logging in with google does not work; gives the error ""Could not authenticate you from GoogleOauth2 because "Invalid credentials"."
-DOES NOT PASS"

**Comment by pat-son** [comment]
PASSED testing on Chrome 50.0.2661.86 (OSX 10.11.3).
Google login works; can't test password resetting on dev.
