### ISSUE TITLE
Time Period option always available. 

### ISSUE THREAD

**Issue by jdalphon** [isenseDev/rSENSE#2388]
The problem that the period option may not make sense to all users if there is no Timestamp field associated with the data. This causes all sorts of wierd and somewhat undesirable results. 

I realize that there is an OFF option, but this whole tool should probably not be shown unless there is a timestamp associated with the project.

@mmcguinn @jaypoulz Would you like to weight in from beyond the UML grave?

**Comment by mmcguinn** [comment]
@jdalphon I feel like I've been summoned up by some sort of dark ritual.

I've poked around with the feature and had a look at the code. It just seems like something that should only be present in the timeline vis - but it's been added to scatter in general. I'd also note that it needs to be turned off if GeoTime is active (since that means you only have a number of years); right now if you try to use it on data that's in GeoTime mode (like in this experiment [this] (http://isenseproject.org/projects/154/data_sets/1543)) it behaves oddly as I would expect.

**Comment by bdonald25** [comment]
@pat-son I agree this should not be shown if there is no time data. 

@mmcguinn It is actually available for all the vises not just timeline and scatter. The period option itself should only affect timeline, but having it enabled also allows you to group by period which is useful for all the vises.

**Comment by pat-son** [comment]
@jdalphon That was an oversight on my part - originally the period option _was_ only in the Timeline vis, so it didn't need to be turned off when there was no time data (because the Timeline was already off anyway). But then Bobby suggested that it should be present for the other vises as well for the group-by option. So that's what we did, but I forgot to turn it off when there was no time data. I also forgot to add a check that the current vis is Timeline when modifying dates; that's what's causing the weirdness on the x-axis in the scatter plot when Period is on. Should be a one-line fix for each of those issues.

@mmcguinn The period code is in the general scatter file instead of the timeline file because timeline extends so heavily from scatter that it made more sense to do it that way. The only function that needed to be modified to add the feature was update(). Timeline doesn't have it's own update(), and I only had to change <20 lines in the function, so it made more sense to add it there instead of copying over a bunch of code from scatter.coffee into timeline.coffee (DRY). 

As Bobby said, the feature also exists in other Vises so that you can use the period group-by option.

As for the GeoTime, that should be fixed along with the other scatter fix, since it looks like at that point the timeline vis is just a normal scatter plot.
Where does Geo Time get set? I only see one reference to @GEO_TIME_MODE in the entire code base, where it's used in scatter.coffee.

**Comment by mmcguinn** [comment]
@bdonald25 Ah neat, I didn't see that it also allowed grouping! That is certainly useful.

As for the Geo time - it gets set [here](https://github.com/isenseDev/rSENSE/blob/master/app/assets/javascripts/visualizations/highvis/highmodifiers.coffee#L432) and then gets picked up by timeline [here](https://github.com/isenseDev/rSENSE/blob/e9ff7127b160056d19d31c158fc1ccb2579f72a8/app/assets/javascripts/visualizations/highvis/timeline.coffee#L102). 

As far as conditions to allow the period grouping, I think then that only turning it on with both `data.timeType is data.NORM_TIME` and you've got at least one time field would make sense.

@pat-son The reference you pointed out led me on a rather wild goose chase back to [May 23 2013](https://github.com/isenseDev/rSENSE/commit/0e476fb5f349bfaa05ed0d0db30aa2b37671729d) written by myself. That little control statement regarding @timeMode and @GEO_TIME_MODE is totally dead code though - @timeMode isn't defined by anything so it never runs. What it's trying to do there is obviously wrong (It's trying to use Date when GEO_TIME is on - which would fail) as well. Nice little treasure chest of dead, bad code I seem to have left there :-)

**Comment by pat-son** [comment]
@mmcguinn Looks like it's safe to delete that code block then. Good to know.

**Comment by pat-son** [comment]
Testers: Go to a visualization without time data. make sure that Time Period and Group by Time Period are not available.
Go to a visualization that has time data. Go to the Scatter vis. Turn on Period, and make sure that the x-axis values are not changed.

**Comment by pat-son** [comment]
PASSED testing on Chrome 50.0.2661.102 (Windows 10).
