### ISSUE TITLE
Borders on bars are obscuring other bars in the Bar Chart vis

### ISSUE THREAD

**Issue by smichalka** [isenseDev/rSENSE#2487]
http://isenseproject.org/projects/866/data_sets/

Happens in two different web browsers.  Other visualizations are fine.

![screenshot 2](https://cloud.githubusercontent.com/assets/5709961/18327598/4db38102-7519-11e6-8c05-4d6c540b918f.png)

**Comment by pat-son** [comment]
The issue here isn't that there are two x-axes. The problem is that bars have a white border with a width of 4 pixels, which is obscuring parts/all of the bars because they are so thin. The solution here would be to disable the white border either all the time or only when the bars are thin/close together enough.
Here's what I'm talking about:
Default border (white, 4px):
![obscured-borders](https://cloud.githubusercontent.com/assets/8462638/18359897/e7802186-75c9-11e6-830d-e4596136a422.png)

No borders:
![no-borders](https://cloud.githubusercontent.com/assets/8462638/18359905/ee88d16c-75c9-11e6-8a9a-e3b20980ed37.png)

**Comment by pat-son** [comment]
I would rather keep the borders, as they act as a nice spacer when working with normal-sized bars. What we need to do, then, is decide how small the bars should be before turning the border off.

Another option is to let the user decide whether to keep the borders or not.

**Comment by fgmart** [comment]
But Patrick why is both Dissolved Oxygen and Temperature showing up on the
X axis?

I thought we couldn't display two side-by-side histograms?

**Comment by doug-salvati** [comment]
This is two side-by-side bar graphs, which is allowed.  It could be confusing to users, but it's not a bug.
The borders are a good point though.  I don't see the value in keeping the borders but if they're staying they need to vanish when the bars are within 4px of each other.

**Comment by pat-son** [comment]
@fgmart I don't know if I was misinterpreting the issue, but you've always been able to have multiple bar groups.

**Comment by pat-son** [comment]
@doug-salvati Without the borders, bars will draw with no spacing, which looks a little unsightly. The other option would be to add in spacing manually instead of using the borders, but that would still require us to reduce the amount of spacing when there are many bars.

**Comment by fgmart** [comment]
Oh! This is me being confused; I was just assuming histogram.

I sort of like the automatic borders-off idea.

**Comment by pat-son** [comment]
See [here](https://github.com/isenseDev/rSENSE/blob/757f97d530e409c4c6fd282a18ee606908d6e724/app/assets/javascripts/visualizations/highvis/bar.coffee#L184): We set bars to have 0 padding by default. Instead of the borders, we could have a function that adds spacing depending on how many bars there are.

**Comment by pat-son** [comment]
Testers: Go to [this project](http://rsense-dev.cs.uml.edu/projects/866/data_sets/) and make sure that the bars look okay.

**Comment by doug-salvati** [comment]
PASSED testing on Chrome 53.0.2785.143 (OSX 10.11.6).

**Comment by doug-salvati** [comment]
Testers: Be sure to deselect all and then just select a few. Make sure there is padding when there are only a few selected

**Comment by mck529** [comment]
PASSED testing on Chrome 53.0.2785.101 (linux).

**Comment by VictoriaAlbanese** [comment]
PASSED testing on Chrome 48.0.2564.116 (linux).
