### ISSUE TITLE
Standard Deviation (Teacher request)

### ISSUE THREAD

**Issue by pat-son** [isenseDev/rSENSE#2540]
Would probably go in summary vis.

**Comment by mdibello** [comment]
PASSED testing on Chrome 54.0.2840.100 (Ubuntu 16.04.1 LTS).
The addition of a seventh summary page value breaks the balance of two rows of three boxes. The boxes containing the values are now arranged like this:
X X X
X X X
X
We might want to center the final box so that it's in the middle (separate issue).

**Comment by mck529** [comment]
PASSED testing on Chrome 54.0.2840.90 (Ubuntu 16.04).

**Comment by doug-salvati** [comment]
PASSED testing on Chrome 54.0.2840.90 (linux).
