### ISSUE TITLE
Create a script for database backup

### ISSUE THREAD

**Issue by tylerpuleo** [isenseDev/rSENSE#2577]
Maybe make this run automatically weekly or something?

**Comment by doug-salvati** [comment]
Do we have documentation of the process currently used for manual backup?

**Comment by bdonald25** [comment]
@doug-salvati  From beyond the grave. 

It is something like this but test locally first, I am not responsible if things go wrong because it has been awhile since I have done it. Essentially you are just dumping to the file and then putting the file somewhere safe so you can restore to from later. Should be easy to automate.

```
# dump the development db to a file
rake db:dump
# dump the production db to a file
RAILS_ENV=production rake db:dump 

# restore to development db from file. 
rake db:restore
# restore to the production from the file.
RAILS_ENV=production rake db:restore
```

**Comment by pat-son** [comment]
Since we're moving to AWS and possibly using their automated backups, this is going on the back burner for now.

**Comment by chikeabuah** [comment]
solved by rds automated backups
