### ISSUE TITLE
Add email verification

### ISSUE THREAD

**Issue by VictoriaAlbanese** [isenseDev/rSENSE#2604]
You can make your email address fake.
We should make it so that you need to verify your email address.

**Comment by doug-salvati** [comment]
Testers: this will need to be tested over the course of a day due to the 24-hour grace period.  For now, create a user and make sure an alert comes up stating that a link was sent to their email.  You can also checkout /users/confirmation/new if you want.  When we're live, I will create a new account and make sure the emails all work properly, however I did test this on localhost already.

**Comment by VictoriaAlbanese** [comment]
FAILED testing on Chrome 54.0.2840.71 (linux).

**Comment by doug-salvati** [comment]
PASSED testing on Chrome 54.0.2840.90 (linux).
