### ISSUE TITLE
filter seems broken for equals comparison

### ISSUE THREAD

**Issue by fgmart** [isenseDev/rSENSE#2778]
Go to http://isenseproject.org/projects/3177/data_sets
Put 15 into the Age filter (leave the setting on ==)
It seems to work; only data sets with age = 15 are shown.

Then, turn Filtering to On and click "Set Current Filters"

All of the data sets disappear!

Note: < and <= do seem to work.

**Comment by theyoyojo** [comment]
The "not =" operator ('!') does not seem to work either.

On: http://isenseproject.org/visualizations/1252

I entered a value of 15 in the temperature category.

The filters seem to be applied temporarily. As an example:

`filters: "{"groupOp":"AND","rules":[{"field":"temperature_(°c)","op":"eq","data":"15"}]}"`

This is the filters value for `@table.getGridParam('postData')` (located in table.coffee in js/visualizations/) when the filter is applied temporarily by entering the value into the search bar.

Once is is applied through the "Set Current Filters" button, the rules value of filters is cleared and the filtering is implemented through a different mechanism. As you can see below, even with the '!' applied as a filter for the value 15 in the temperature column, I am still able to search for and find all of the rows with a temperature value of 15. I would expect that the table would be empty.

![screenshot from 2017-12-18 15-25-33](https://user-images.githubusercontent.com/1909841/34126499-c2420986-e407-11e7-96f7-f45b21f0e503.png)

Investigation of this issue is ongoing.

**Comment by doug-salvati** [comment]
PASSED testing on Safari 11.0.3 (mac).

**Comment by Josh-Everett** [comment]
PASSED testing on Safari 11.1 (mac).

**Comment by VictoriaAlbanese** [comment]
PASSED testing on Chrome 65.0.3325.181 (windows).
